
"""
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
purpose:-programm to implement coupen problem
@author:-Sheevendra Singh Singhraul
@version:-3.8.6
@since:-22-03-2021
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
"""
import random
coupen=int(input("enter how many coupens you wanted to find="))
coupenStore=[]
temp=[]
while True:
    element=int(input("enter coupen="))
    if element in coupenStore:
        print("you have entered element which is already exist into coupens")
        print("so i will not store this same coupen to coupen store")
        pass
    else:
        coupenStore.append(element)
        if len(coupenStore)==coupen:
            break
print("you have entered these coupens=",coupenStore)

maxCoupen=max(coupenStore)

temp = []

while True:
    ele=random.randint(0,maxCoupen)
    if ele in coupenStore and ele not in temp:
        temp.append(ele)
    else:
        pass
    if len(temp)==len(coupenStore):
            break

print("coupens generated by random =",temp)